#!/usr/bash#
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

apt-get update
apt-get install -y haproxy

printf %s"
frontend hbnb-lb_front
        tbind *:80
        tmode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        tbalance roundrobin
        server 1723-web-01 100.26.181.86:80 check
        server 1723-web-02 34.238.192.13:80 check
">> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
